### ISSUE TITLE
Bad argument exception

### ISSUE THREAD

**Issue by Gert-dev** [recca0120/tester-phpunit#2]
Hello

Is there possibly an error [in the spawn-runner file](https://github.com/recca0120/tester-phpunit/blob/master/lib/spawn-runner.js#L86)? The `command` passed here is an array that is returned by `getCommand`, but `BufferedProcess` expects a string instead of an array here.

I had to change this in order to get past a `Bad argument` exception.

Thanks in advance

**Comment by recca0120** [comment]
Hello

fixed in 0.2.0

**Comment by Gert-dev** [comment]
Thanks!
