### ISSUE TITLE
Show error message feedback in marker

### ISSUE THREAD

**Issue by Gert-dev** [recca0120/tester-phpunit#3]
Hello

It would be neat if the actual error output from PHPUnit could be shown when a test is failing. This prevents having to open the panel all the time.

I noticed that you _can_ get some kind of error message to show when using the `Show inline errors after test run` option from tester, but it's not always very useful as it shows messages like `PhpUnit\Framework\ExpectationFailedException`.

Thanks in advance

**Comment by recca0120** [comment]
Hello

fixed in new tester version. 

I didn't do anything..
