### ISSUE TITLE
spawn-runner prefers phpunit.xml.dist over phpunit.xml

### ISSUE THREAD

**Issue by Gert-dev** [recca0120/tester-phpunit#5]
Hello

Currently spawn-runner seems to prefer `phpunit.xml.dist` over `phpunit.xml`, if it is present. I think this should be the other way around, as `phpunit.xml.dist` is a file that most projects ship as template for the user to customize in a file called `phpunit.xml`. In other words, `phpunit.xml` may contain user preferences which are currently ignored.

Thanks!

**Comment by recca0120** [comment]
spawn-runner prefer phpunit.xml over phpunit.xml.dist now.

**Comment by Gert-dev** [comment]
Great, thanks!
