### ISSUE TITLE
spawn-runner generates error when test class is abstract

### ISSUE THREAD

**Issue by Gert-dev** [recca0120/tester-phpunit#6]
Hello

It appears there is a (minor) error when attempting to test a class that is abstract. This happens because PHPUnit generates an error that the test "could not be found" (whilst it is in fact abstract and PHPUnit simply can't instantiate it).

Because PHPUnit fails, it does not create a JUnit log file and the package generates an error ` Could not parse data to JSON.`.

PHPUnit skips this test class when running all the tests at once, so the error only seems to occur when you request to test this class by specifying the file, like this package does. Perhaps it would be interesting to bail out early if the JUnit file does not exist or PHPUnit returned an error status for the file?

I'm testing with PHPUnit 6.1.3.

Thanks in advance

**Comment by recca0120** [comment]
fixed.

when create JUnit fail, it will show skipped in Tester Results.

I'm testing with PHPUnit 5.7.19

**Comment by Gert-dev** [comment]
That seems to have fixed it, it is indeed now listed as skipped test, thanks!
